<?php
$data1=array(
    "0"=>array(
        "src"=>"./src/img/foryou1.jpg",
        "title"=>"日本贝亲宽口玻璃奶瓶160ml",
        "des"=>"陪ss奶嘴玻璃质地易冲奶易刷洗",
        "new"=>129.00,
        "old"=>199.00,
        "buy"=>"马上抢",
        "go"=>"14070人已买"
    ),
    "1"=>array(
        "src"=>"./src/img/foryou2.jpg",
        "title"=>"加州宝宝香茅驱蚊液59ml",
        "des"=>"植物草本配方",
        "new"=>35.80,
        "old"=>128.00,
        "buy"=>"马上抢",
        "go"=>"22135人已买"
    ),
    "2"=>array(
        "src"=>"./src/img/foryou3.jpg",
        "title"=>"日本贝亲宽口玻璃奶瓶160ml",
        "des"=>"陪ss奶嘴玻璃质地易冲奶易刷洗",
        "new"=>35.90,
        "old"=>135.00,
        "buy"=>"马上抢",
        "go"=>"2511人已买"
    ),
    "3"=>array(
        "src"=>"./src/img/foryou4.jpg",
        "title"=>"美国五个小卡车棉柔巾8包",
        "des"=>"800抽 100%纯棉 干湿两用",
        "new"=>59.90,
        "old"=>280.00,
        "buy"=>"马上抢",
        "go"=>"1233人已买"
    ),
    "4"=>array(
        "src"=>"./src/img/foryou5.jpg",
        "title"=>"美国五个小卡车安全防护",
        "des"=>"时刻保护宝宝安全玩耍无忧",
        "new"=>59.00,
        "old"=>198.00,
        "buy"=>"马上抢",
        "go"=>"57人已买"
    ),
    "5"=>array(
        "src"=>"./src/img/foryou6.jpg",
        "title"=>"可么奶嘴拆单个组合",
        "des"=>"宝宝喜欢，乳感奶嘴",
        "new"=>55.00,
        "old"=>86.00,
        "buy"=>"马上抢",
        "go"=>"444人已买"
    ),
    "6"=>array(
        "src"=>"./src/img/foryou7.jpg",
        "title"=>"鲁茜婴儿蒸煮一体辅食机",
        "des"=>"蒸煮搅拌一体 妈妈变大厨",
        "new"=>149.00,
        "old"=>898.00,
        "buy"=>"马上抢",
        "go"=>"890人已买"
    ),
    "7"=>array(
        "src"=>"./src/img/foryou8.jpg",
        "title"=>"Pouch欧式可作躺餐椅",
        "des"=>"双餐盘设计，一椅四用",
        "new"=>469.00,
        "old"=>2199.00,
        "buy"=>"马上抢",
        "go"=>"1169人已买"
    ),
    "8"=>array(
        "src"=>"./src/img/foryou9.jpg",
        "title"=>"蓝漂28卷本色空芯卷纸",
        "des"=>"食品级认证，母婴可用加倍柔韧",
        "new"=>27.90,
        "old"=>59.00,
        "buy"=>"马上抢",
        "go"=>"6669人已买"
    ),
    "9"=>array(
        "src"=>"./src/img/foryou1.jpg",
        "title"=>"日本贝亲宽口玻璃奶瓶160ml",
        "des"=>"陪ss奶嘴玻璃质地易冲奶易刷洗",
        "new"=>129.00,
        "old"=>199.00,
        "buy"=>"马上抢",
        "go"=>"14070人已买"
    )  
    );
   
    echo json_encode($data1);
?>